GET http://localhost:3000/api/Categories

###

GET http://localhost:3000/api/categorias/2

###

POST http://localhost:3000/api/categories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJodHRwOi8vd3d3LnczLm9yZy8yMDAxLzA0L3htbGRzaWctbW9yZSNobWFjLXNoYTI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZ3ZlcmFAdXYubXgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJHdWlsbGVybW8gSHVtYmVydG8gVmVyYSBBbWFybyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJleHAiOjE3MTcxOTI0MDcsImlzcyI6IlNlcnZpZG9ySldUUGFyYVByb2dyYVNlZ3VyYSIsImF1ZCI6IkNsaWVudGVzSldUUGFyYVByb2dyYVNlZ3VyYSJ9.li3QZFehWLNbDCOpBa2qBp4jfmeJ7sM4vuJJloQFKSE


{
    "Name": "Categoria de prueba 3"
}

###

PUT http://localhost:3000/api/categorias/16
Content-Type: application/json

{
    "categoriaid": 16,
    "nombre": "Categoria de prueba editada"
}

###

DELETE http://localhost:3000/api/categorias/16